services:
  postgres-logs:
    image: postgres:16
    environment:
      POSTGRES_DB: logs
      POSTGRES_USER: logs
      POSTGRES_PASSWORD: logs
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"